export const englishSubjectLearningAreas = {
  basics: {
    defaultTopic: "numberSystems",
    topics: {
      numberSystems: {
        nav: "Number Systems",
        title: "Binary, hexadecimal and two's complement",
        copy: "Number representation is exam-relevant because mistakes often happen around place value, the sign bit and overflow.",
        learningGoals: ["Read binary and hexadecimal notation", "Build two's complement step by step", "Explain the overflow rule"],
        explanation: "In binary, every position represents a power of two. In two's complement, the most significant bit carries the sign. To represent a negative number, invert the positive bit pattern and add 1. Typical mistake: the least significant bit does not decide the sign; the leftmost bit does.",
        concepts: [
          ["Place value", "1011₂ means 8 + 0 + 2 + 1 = 11."],
          ["Two's complement", "Invert the bits and add 1; this makes signed addition technically uniform."],
          ["Overflow", "Adding two numbers with the same sign can produce a result with the wrong sign."],
        ],
        visualization: {
          title: "8-bit representation",
          type: "bit-grid",
          bits: "11111011",
          rows: [
            ["Start", "+5 = 00000101"],
            ["Invert", "11111010"],
            ["Add 1", "11111011 = -5"],
          ],
        },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Build two's complement",
            question: "Which 8-bit pattern represents -5 in two's complement?",
            choices: ["11111011", "10000101", "11111010", "00000101"],
            answer: "11111011",
            hint: "Start with +5 = 00000101, invert all bits and add 1.",
            explanation: "00000101 becomes 11111010; adding 1 gives 11111011. The leftmost bit indicates a negative value.",
            commonMistakes: {
              "10000101": "That is sign-magnitude thinking. In two's complement you do not simply set a sign bit.",
              "11111010": "You inverted the bits but forgot the final +1.",
            },
            solution: "00000101 -> 11111010 -> 11111011.",
            examRelevance: "Very common in exams on number representation and overflow.",
          },
        ],
        examTasks: [
          {
            type: "multi",
            level: 4,
            title: "Detect overflow",
            question: "Which statements about 8-bit two's complement are correct?",
            choices: [
              "01111111 + 00000001 causes overflow.",
              "The most significant bit determines the sign.",
              "11111111 represents +255.",
              "Overflow can occur when adding two positive numbers.",
            ],
            answer: [
              "01111111 + 00000001 causes overflow.",
              "The most significant bit determines the sign.",
              "Overflow can occur when adding two positive numbers.",
            ],
            hint: "Compare the signs before and after the addition.",
            explanation: "127 + 1 turns into 10000000, which is in the negative range. 11111111 is -1 in two's complement, not +255.",
            solution: "Statements 1, 2 and 4 are correct. Statement 3 confuses unsigned representation with two's complement.",
          },
        ],
      },
      boolean: {
        nav: "Boolean Algebra",
        title: "Truth tables, DNF and CNF",
        copy: "Boolean algebra tests whether you can evaluate logical expressions and recognize normal forms structurally.",
        learningGoals: ["Read logical operators", "Distinguish DNF and CNF", "Use truth tables as a checking tool"],
        explanation: "A DNF is an OR of AND-blocks. A CNF is an AND of OR-blocks. Exam trick: look at the top-level operator first, not only at the inner brackets.",
        concepts: [
          ["DNF", "OR of conjunctions, for example (A ∧ B) ∨ (¬A ∧ C)."],
          ["CNF", "AND of disjunctions, for example (A ∨ B) ∧ (¬A ∨ C)."],
          ["Canonical forms", "Every block contains all variables."],
        ],
        visualization: { title: "Expression tree", type: "logic-tree", nodes: ["∨", "A ∧ B", "¬A ∧ C"] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Recognize a normal form",
            question: "Which form is (A ∧ B) ∨ (¬A ∧ C)?",
            choices: ["DNF", "CNF", "Neither", "Automaton"],
            answer: "DNF",
            hint: "The top-level operator is OR between AND-blocks.",
            explanation: "The expression is a disjunction of conjunctions, so it has DNF structure.",
            solution: "Top level: ∨. Below it: two ∧ terms. Therefore DNF.",
          },
        ],
        examTasks: [
          {
            type: "truefalse",
            level: 4,
            title: "Justify CNF/DNF",
            question: "(A ∨ B) ∧ (¬A ∨ C) is a CNF.",
            choices: ["True", "False"],
            answer: "True",
            hint: "CNF means: AND of OR-blocks.",
            explanation: "The top-level operator is ∧ and the inner brackets are OR terms. That is CNF.",
            solution: "True, because (A ∨ B) and (¬A ∨ C) are disjunctions connected by AND.",
          },
        ],
      },
      automata: {
        nav: "Automata",
        title: "Finite automata and grammars",
        copy: "Automata make states, transitions and accepted words precise.",
        learningGoals: ["Read states and transitions", "Simulate acceptance", "Separate automata from grammars"],
        explanation: "A finite automaton processes a word symbol by symbol. After each symbol it follows a transition. At the end, the reached state decides whether the word is accepted.",
        concepts: [
          ["Start state", "The state where processing begins."],
          ["Accepting state", "If processing ends here, the word is accepted."],
          ["Transition", "A rule such as: from state q with symbol a go to state p."],
        ],
        visualization: {
          title: "Mini automaton for an even number of 1s",
          type: "automaton",
          states: ["q0 Start/Accept", "q1"],
          transitions: ["q0 --1--> q1", "q1 --1--> q0", "0 keeps the current state"],
        },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Check acceptance",
            question: "An automaton switches between q0 and q1 on every 1. q0 is accepting. Is 101 accepted?",
            choices: ["Yes", "No", "Only if 0 is forbidden", "Undecidable"],
            answer: "Yes",
            hint: "Count only the ones: 101 contains two ones.",
            explanation: "Start in q0, first 1 to q1, 0 stays, second 1 back to q0. q0 is accepting.",
            solution: "q0 --1--> q1 --0--> q1 --1--> q0. Accepted.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Explain the language",
            question: "Briefly describe the language accepted by an automaton that switches state on every 1 and has q0 as accepting state.",
            answer: ["even", "number", "1"],
            hint: "What property is the automaton counting?",
            explanation: "A good answer mentions an even number of ones. Zeros do not change the parity.",
            solution: "The automaton accepts all words with an even number of 1s.",
          },
        ],
      },
      computerSystems: {
        nav: "Computer Systems",
        title: "Memory hierarchy and computer basics",
        copy: "Computer systems connect hardware, memory types and the trade-off between access speed and persistence.",
        learningGoals: ["Distinguish SRAM and DRAM", "Order the memory hierarchy", "Explain volatility"],
        explanation: "The closer memory is to the CPU, the faster and usually smaller it is. Registers and cache are very fast, main memory is larger, SSD storage is persistent but slower.",
        concepts: [
          ["SRAM", "Very fast and expensive; typically used for cache."],
          ["DRAM", "Main memory; needs regular refreshing."],
          ["Persistence", "Data remains after power-off, for example on SSD storage."],
        ],
        visualization: { title: "Memory hierarchy", type: "pipeline", steps: ["Registers", "Cache/SRAM", "RAM/DRAM", "SSD", "Archive"] },
        guidedTasks: [
          {
            type: "single",
            level: 1,
            title: "Classify memory",
            question: "Which memory type is typically used for cache?",
            choices: ["SRAM", "DRAM", "SSD", "Magnetic tape"],
            answer: "SRAM",
            hint: "Cache needs especially fast access.",
            explanation: "SRAM is fast and expensive, so it is suitable for small cache memories.",
            solution: "Cache -> SRAM; main memory -> DRAM; persistent storage -> SSD/HDD.",
          },
        ],
        examTasks: [
          {
            type: "multi",
            level: 4,
            title: "Justify memory hierarchy",
            question: "Which statements about memory hierarchy are correct?",
            choices: ["Registers are very fast and very small.", "SSD is more volatile than RAM.", "DRAM is typically used as main memory.", "Cache is conceptually closer to the CPU than SSD."],
            answer: ["Registers are very fast and very small.", "DRAM is typically used as main memory.", "Cache is conceptually closer to the CPU than SSD."],
            hint: "Order by CPU proximity and persistence.",
            explanation: "SSD is not more volatile than RAM; it is persistent. Registers, cache and RAM are faster but volatile.",
            solution: "Statements 1, 3 and 4 are correct.",
          },
        ],
      },
    },
  },
  programming: {
    defaultTopic: "javaOop",
    topics: {
      javaOop: {
        nav: "Java OOP",
        title: "Classes, constructors and inheritance",
        copy: "Java exercises often test whether you clearly separate object state, constructors, overriding and interfaces.",
        learningGoals: ["Recognize constructors", "Explain inheritance", "Separate overriding from overloading"],
        explanation: "A class is a blueprint. A constructor initializes new objects. Overriding means that a subclass provides a new implementation for the same method signature. Overloading means same method name but a different parameter list.",
        concepts: [
          ["Constructor", "Has no return type and uses the class name."],
          ["Override", "Same signature in a subclass, different implementation."],
          ["Interface", "Defines a behavioral contract without necessarily storing state."],
        ],
        visualization: { title: "Inheritance hierarchy", type: "uml", boxes: ["Person", "Student extends Person", "Lecturer extends Person"] },
        guidedTasks: [
          {
            type: "multi",
            level: 2,
            title: "Understand constructors",
            snippet: ["class Account {", "  private int balance;", "  Account(int start) {", "    balance = start;", "  }", "}"].join("\n"),
            question: "Which statements are correct?",
            choices: ["Account(int start) is a constructor.", "The constructor has no return type.", "balance is local to the constructor.", "start initializes object state."],
            answer: ["Account(int start) is a constructor.", "The constructor has no return type.", "start initializes object state."],
            hint: "Look at the class name, the missing return type and the field access.",
            explanation: "balance is a field of the class. The constructor sets that field using the parameter start.",
            solution: "Statements 1, 2 and 4 are correct.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Translate UML to Java",
            question: "A UML class Book has an attribute title:String and a method getTitle():String. Which Java building blocks must appear in the class?",
            answer: ["class", "String", "getTitle"],
            hint: "Name the class declaration, field and method.",
            explanation: "A suitable answer contains a class Book, a String field title and a method String getTitle().",
            solution: "class Book { private String title; String getTitle() { return title; } }",
          },
        ],
      },
      javaReferences: {
        nav: "Java References",
        title: "References vs. object copies",
        copy: "A common exam mistake is assuming that a = b copies an object. In Java, only the reference is copied.",
        learningGoals: ["Explain reference assignment", "Detect aliasing effects", "Distinguish objects from variables"],
        explanation: "Object variables store references. After a = b, both variables refer to the same object. Changes through a are visible through b because there is only one object.",
        concepts: [
          ["Reference", "A link to an object on the heap."],
          ["Alias", "Several variables refer to the same object."],
          ["Copy", "Requires explicitly creating or copying a new object."],
        ],
        visualization: {
          title: "Before/after a = b",
          type: "reference",
          before: ["a -> Object A", "b -> Object B"],
          after: ["a -> Object B", "b -> Object B", "Object A without reference"],
        },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Reference assignment",
            question: "What happens with a = b when a and b are object variables?",
            choices: ["a then refers to the same object as b.", "The object of b is fully copied.", "b then points to a.", "Both objects are deleted."],
            answer: "a then refers to the same object as b.",
            hint: "In Java, object variables are references.",
            explanation: "The reference is copied, not the object. Afterwards two variables point to the same object.",
            commonMistakes: { "The object of b is fully copied.": "That is the classic mistake. A real copy would require a new object, for example via a constructor or clone logic." },
            solution: "After a = b, a and b refer to the same object.",
          },
        ],
        examTasks: [
          {
            type: "single",
            level: 4,
            title: "Aliasing effect",
            snippet: ["Box a = new Box(1);", "Box b = new Box(2);", "a = b;", "a.value = 7;", "System.out.println(b.value);"].join("\n"),
            question: "What is printed?",
            choices: ["7", "2", "1", "Compiler error"],
            answer: "7",
            hint: "After a = b both variables refer to the same Box.",
            explanation: "a.value changes the object also referenced by b. Therefore b.value reads 7.",
            solution: "Output: 7.",
          },
        ],
      },
      python: {
        nav: "Python",
        title: "Control flow, functions and collections",
        copy: "Python exercises often test whether you can read loops, list mutation and dictionaries precisely step by step.",
        learningGoals: ["Evaluate loops", "Recognize list mutation", "Understand dictionary access"],
        explanation: "Python code is often close to pseudocode. Still, mutation and indentation are decisive: append changes a list, and wrong indentation changes control flow.",
        concepts: [["List", "Ordered, mutable collection."], ["Dictionary", "Key-value structure with fast lookup by key."], ["Function", "Encapsulates steps and can return values."]],
        visualization: { title: "List mutation", type: "table", headers: ["Step", "List"], rows: [["Start", "[1, 2]"], ["append(3)", "[1, 2, 3]"], ["pop(0)", "[2, 3]"]] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Python output",
            snippet: ["values = [1, 2]", "values.append(3)", "print(values[1])"].join("\n"),
            question: "What is printed?",
            choices: ["2", "3", "[1, 2, 3]", "IndexError"],
            answer: "2",
            hint: "Python indices start at 0.",
            explanation: "After append, the list is [1, 2, 3]. Index 1 is the second element, so it is 2.",
            solution: "Output: 2.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Find the code error",
            snippet: ["def total(xs):", "total = 0", "for x in xs:", "    total += x", "return total"].join("\n"),
            question: "Which typical Python error appears in this code?",
            answer: ["indentation", "indent"],
            hint: "Which lines belong to the function body?",
            explanation: "The function body must be indented. total = 0 and return total are currently not in the block.",
            solution: "The indentation after def is wrong; the function body must be indented.",
          },
        ],
      },
      cpp: {
        nav: "C++",
        title: "C++ basics",
        copy: "C++ connects syntax with memory thinking. For fundamentals, loops, types, vectors and references are enough.",
        learningGoals: ["Read for-loops", "Distinguish value and reference", "Know basic vector operations"],
        explanation: "In C++, types are often explicit. References with & can modify an existing value, while ordinary assignments often copy.",
        concepts: [["std::vector", "Dynamic array with push_back and index access."], ["Reference &", "Alias for an existing value."], ["Compiler", "Translates code before execution."]],
        visualization: { title: "Vector layout", type: "array", values: ["Index 0: 4", "Index 1: 7", "Index 2: 9"] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            snippet: ["int sum = 0;", "for (int i = 1; i <= 3; i++) {", "  sum += i;", "}"].join("\n"),
            title: "C++ loop",
            question: "Which value is stored in sum at the end?",
            choices: ["6", "3", "4", "9"],
            answer: "6",
            hint: "The loop runs for i = 1, 2, 3.",
            explanation: "The code adds 1 + 2 + 3.",
            solution: "sum = 6.",
          },
        ],
        examTasks: [
          {
            type: "truefalse",
            level: 4,
            title: "Understand references",
            question: "A C++ reference can act as an alias for an existing variable.",
            choices: ["True", "False"],
            answer: "True",
            hint: "Think of int& r = x.",
            explanation: "A reference can make changes visible on the original value.",
            solution: "True. int& r = x; r = 5; changes x.",
          },
        ],
      },
    },
  },
  dataScience: {
    defaultTopic: "relations",
    topics: {
      relations: {
        nav: "Relations",
        title: "Relations, keys and functional dependencies",
        copy: "Database exams often test whether you can apply key minimality and attribute closure correctly.",
        learningGoals: ["Distinguish relation, tuple and attribute", "Separate superkeys from candidate keys", "Compute attribute closure"],
        explanation: "A superkey uniquely identifies tuples but may contain unnecessary attributes. A candidate key is a minimal superkey. Functional dependencies tell you which attributes follow from a given attribute set.",
        concepts: [["Superkey", "Guarantees uniqueness but may contain redundant attributes."], ["Candidate key", "Minimal superkey without unnecessary attributes."], ["Attribute closure", "All attributes that functionally follow from a set."]],
        visualization: { title: "Attribute closure", type: "closure", steps: ["Start: A+ = {A}", "Apply A -> B: {A, B}", "Apply B -> C: {A, B, C}", "A is a candidate key"] },
        guidedTasks: [
          {
            type: "multi",
            level: 2,
            title: "Find candidate keys",
            question: "Given R(A,B,C) with A -> B and B -> C. Which attribute sets are candidate keys?",
            choices: ["{A}", "{A,B}", "{B}", "{A,C}"],
            answer: ["{A}"],
            hint: "Compute A+ and then check minimality.",
            explanation: "A determines B and, through B, also C. {A,B} is unique but not minimal.",
            commonMistakes: { "{A,B}": "{A,B} is a superkey, but not a candidate key because A alone is sufficient.", "{B}": "B determines C, but not A. One attribute is missing." },
            solution: "A+ = {A,B,C}. Therefore {A} is the candidate key.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Justify minimality",
            question: "Why is {A,B} not a candidate key in this example, even though {A,B} determines all attributes?",
            answer: ["not minimal", "a alone"],
            hint: "Candidate keys must be minimal.",
            explanation: "{A,B} contains redundant B because A alone already determines A, B and C.",
            solution: "{A,B} is only a superkey. The candidate key is {A}, because A alone determines all attributes.",
          },
        ],
      },
      sql: {
        nav: "SQL/MySQL",
        title: "Logical SQL execution order",
        copy: "SQL becomes exam-friendly once you understand the logical order: FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY.",
        learningGoals: ["Separate WHERE and HAVING", "Determine JOIN results", "Explain aggregation"],
        explanation: "WHERE filters rows before grouping. HAVING filters groups after aggregation. A common mistake is putting aggregate conditions such as COUNT(*) > 2 into WHERE.",
        concepts: [["WHERE", "Filters individual rows before GROUP BY."], ["HAVING", "Filters groups after aggregation."], ["JOIN", "Combines tuples according to a condition."]],
        visualization: { title: "Logical SQL order", type: "pipeline", steps: ["FROM/JOIN", "WHERE", "GROUP BY", "HAVING", "SELECT", "ORDER BY"] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Recognize HAVING",
            snippet: ["SELECT customer_id, COUNT(*)", "FROM orders", "GROUP BY customer_id", "HAVING COUNT(*) > 2;"].join("\n"),
            question: "Why is COUNT(*) > 2 written in HAVING?",
            choices: ["Because it filters aggregated groups.", "Because WHERE cannot contain numbers.", "Because SELECT always comes last.", "Because GROUP BY is removed by it."],
            answer: "Because it filters aggregated groups.",
            hint: "COUNT(*) exists only after grouping.",
            explanation: "Conditions on aggregates belong in HAVING because WHERE is evaluated before aggregation.",
            solution: "HAVING COUNT(*) > 2 filters customer groups with more than two orders.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Write SQL",
            question: "Write the core of an SQL query that counts orders per customer.",
            answer: ["group by", "count", "customer"],
            hint: "You need SELECT, COUNT and GROUP BY.",
            explanation: "The model answer groups by customer_id and counts rows per group.",
            solution: "SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id;",
          },
        ],
      },
      normalForms: {
        nav: "Normal Forms",
        title: "1NF, 2NF, 3NF and dependencies",
        copy: "Normalization reveals redundancy and prevents update, insert and delete anomalies.",
        learningGoals: ["Distinguish 1NF/2NF/3NF", "Recognize partial dependencies", "Explain transitive dependencies"],
        explanation: "1NF requires atomic values. 2NF forbids partial dependencies on part of a composite key. 3NF forbids transitive dependencies between non-key attributes.",
        concepts: [["1NF", "No lists or repeating groups inside one field."], ["2NF", "Every non-key attribute depends on the whole key."], ["3NF", "Non-key attributes do not determine other non-key attributes."]],
        visualization: { title: "Normalization steps", type: "pipeline", steps: ["Unnormalized table", "1NF: atomic values", "2NF: remove partial dependencies", "3NF: remove transitive dependencies"] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Partial dependency",
            question: "Relation OrderLine(Position, Item, ItemName) has key (Position, Item). Item -> ItemName. Which normal form is violated?",
            choices: ["2NF", "1NF", "BCNF is always satisfied", "None"],
            answer: "2NF",
            hint: "ItemName depends only on Item, not on the whole composite key.",
            explanation: "This is a partial dependency on part of the composite key and violates 2NF.",
            solution: "Item and ItemName should be moved into a separate item table.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Explain a 3NF violation",
            question: "Why does CustomerID -> ZIP and ZIP -> City typically violate 3NF if City is stored in the customer table?",
            answer: ["transitive", "zip", "city"],
            hint: "A non-key attribute determines another non-key attribute.",
            explanation: "City depends transitively on CustomerID through ZIP. This creates redundancy.",
            solution: "CustomerID -> ZIP -> City is transitive; ZIP/City should be separated.",
          },
        ],
      },
      erModeling: {
        nav: "ER Modeling",
        title: "ER modeling from text",
        copy: "ER exercises require deriving entities, relationships and cardinalities from natural language.",
        learningGoals: ["Recognize entities", "Justify cardinalities", "Name relationships clearly"],
        explanation: "Nouns with their own identity are often entities. Verbs between entities point to relationships. Cardinalities follow from phrases such as 'exactly one', 'many' or 'optional'.",
        concepts: [["Entity", "Object class with identity, such as Customer."], ["Relationship", "Connection between entities, such as Customer places Order."], ["Cardinality", "How many objects may or must be related."]],
        visualization: { title: "Mini ER sketch", type: "erd", boxes: ["Customer 1", "places", "n Orders"] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Read cardinality",
            question: "A customer can place many orders; each order belongs to exactly one customer. Which cardinality fits?",
            choices: ["Customer 1:n Order", "Customer n:m Order", "Customer 1:1 Order", "No relationship"],
            answer: "Customer 1:n Order",
            hint: "One customer -> many orders; one order -> one customer.",
            explanation: "From Customer to Order this is 1:n.",
            solution: "Customer 1:n Order.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Name entities",
            question: "Text: Customers order items. An order contains several line items. Name two central entities.",
            answer: ["customer", "order"],
            hint: "Look for things with their own identity.",
            explanation: "Customer and Order are central entities; Item and OrderLine are also plausible.",
            solution: "For example Customer, Order, Item and OrderLine.",
          },
        ],
      },
      pyspark: {
        nav: "PySpark",
        title: "PySpark DataFrames and big-data pipelines",
        copy: "PySpark tasks test whether you can distinguish transformations, actions and pipeline thinking.",
        learningGoals: ["Separate transformations and actions", "Explain DataFrame steps", "Classify lazy evaluation"],
        explanation: "Transformations such as filter or select describe a new DataFrame. Actions such as count or show trigger execution. PySpark often only plans steps until an action is requested.",
        concepts: [["Transformation", "filter, select and groupBy describe data transformations."], ["Action", "count, show and collect trigger computation."], ["DAG", "Dependency graph of processing steps."]],
        visualization: { title: "PySpark pipeline", type: "pipeline", steps: ["read orders", "filter amount > 100", "groupBy customer", "count"] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Transformation or action",
            snippet: "orders.filter(orders.amount > 100).count()",
            question: "Which operation triggers computation?",
            choices: ["count()", "filter()", "orders.amount", "The dot operator"],
            answer: "count()",
            hint: "An action asks for a concrete result.",
            explanation: "filter is a transformation; count is an action and starts execution.",
            solution: "count() triggers the computation.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Explain lazy evaluation",
            question: "Briefly explain why PySpark often evaluates transformations lazily.",
            answer: ["optimize", "plan", "action"],
            hint: "PySpark can improve the execution plan before an action arrives.",
            explanation: "Lazy evaluation enables optimization and avoids unnecessary work until a result is needed.",
            solution: "Transformations build a plan; only an action triggers optimized execution.",
          },
        ],
      },
    },
  },
  informationManagement: {
    defaultTopic: "im",
    topics: {
      im: {
        nav: "Information Management",
        title: "Information needs, sources and use",
        copy: "Information management asks which information an organization needs, where it comes from and how it becomes usable.",
        learningGoals: ["Classify IM layers", "Distinguish information sources", "Understand master data as a resource"],
        explanation: "Information management connects strategic, organizational and technical perspectives. Typical mistake: confusing SQL detail knowledge with information management. Here the focus is on needs, quality, use and governance of information.",
        concepts: [["Information need", "Which information is required for a decision?"], ["Information source", "Internal or external, formal or informal."], ["Master data", "Long-lived core data such as customer, material or supplier."]],
        visualization: { title: "IM layer model", type: "layers", layers: ["Strategy", "Organization", "Application systems", "Data layer"] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Recognize IM focus",
            question: "Which question belongs most clearly to information management?",
            choices: ["Which information does Sales need for decisions?", "What is the SQL syntax for INNER JOIN?", "Which rotation does an AVL tree need?", "How do you iterate over a Python dictionary?"],
            answer: "Which information does Sales need for decisions?",
            hint: "IM starts with the business information need.",
            explanation: "Information management looks at needs, sources, use and quality of information at organizational level.",
            solution: "The Sales question is business-organizational and therefore IM.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Justify master data",
            question: "Why do master data records need globally unique keys?",
            answer: ["unique", "system", "process"],
            hint: "Think of multiple systems and processes.",
            explanation: "Without unique keys, duplicates, wrong assignments and process errors occur across system boundaries.",
            solution: "Unique keys prevent duplicates and enable consistent process and system integration.",
          },
        ],
      },
      erp: {
        nav: "ERP Processes",
        title: "ERP, subledgers and process interaction",
        copy: "ERP systems integrate business processes. Exam tasks often test roles, organizational units and data flows.",
        learningGoals: ["Read ERP process chains", "Classify subledgers", "Understand customer-supplier interactions"],
        explanation: "ERP connects sales, procurement, inventory, production and finance. Subledgers keep detailed transactions that are later summarized in the general ledger. One process step often creates effects in another department.",
        concepts: [["ERP", "Integrated application system for business processes."], ["Subledger", "Detailed accounting such as accounts receivable or accounts payable."], ["Customizing", "Adapting the system to organizational structures and processes."]],
        visualization: { title: "Order-to-cash process", type: "pipeline", steps: ["Sales order", "Delivery", "Goods issue", "Invoice", "Payment"] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Classify subledger",
            question: "Where are open receivables from customers typically tracked in detail?",
            choices: ["Accounts receivable subledger", "Source-code repository", "AVL tree", "CPU register"],
            answer: "Accounts receivable subledger",
            hint: "Receivables from customers belong to accounts receivable.",
            explanation: "The accounts receivable subledger contains customer-specific receivable details that are summarized in the general ledger.",
            solution: "Accounts receivable subledger.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Explain process effects",
            question: "Name two follow-up effects that a goods issue in ERP can typically trigger.",
            answer: ["inventory", "posting"],
            hint: "Think of warehouse and accounting.",
            explanation: "A goods issue reduces inventory and creates accounting effects, for example material or cost postings.",
            solution: "Inventory reduction and accounting posting; invoicing may follow later.",
          },
        ],
      },
      systemSelection: {
        nav: "System Selection",
        title: "Utility analysis and criteria",
        copy: "System-selection tasks test whether you can use must-have, should-have and nice-to-have criteria with justified weights.",
        learningGoals: ["Separate criteria types", "Read utility analysis", "Justify project decisions"],
        explanation: "Must-have criteria are exclusion criteria. Should-have criteria are weighted and scored. Nice-to-have criteria increase value but are not decisive. Typical mistake: trying to compensate for a failed must-have criterion with a high score elsewhere.",
        concepts: [["Must-have criterion", "If it is not met, the system is excluded."], ["Should-have criterion", "Weighted and evaluated."], ["Utility value", "Weighted score used to compare options."]],
        visualization: { title: "Utility matrix", type: "table", headers: ["Criterion", "Weight", "System A", "System B"], rows: [["GDPR", "must", "yes", "no"], ["Cost", "30%", "4", "5"], ["Usability", "20%", "3", "4"]] },
        guidedTasks: [
          {
            type: "single",
            level: 2,
            title: "Must-have criterion",
            question: "A CRM system does not meet a must-have criterion. What follows in a clean selection process?",
            choices: ["It is excluded.", "It still wins if the price is good.", "The must-have becomes nice-to-have.", "It automatically receives full points."],
            answer: "It is excluded.",
            hint: "Must-have means exclusion condition.",
            explanation: "Must-have criteria cannot be compensated by other advantages.",
            solution: "The system is excluded.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Formulate a criterion",
            question: "Formulate a useful must-have criterion for an ERP cloud migration project.",
            answer: ["privacy", "availability", "interface", "compliance"],
            hint: "Think of hard requirements without which the project is not viable.",
            explanation: "Good must-have criteria are testable and project-critical, such as GDPR compliance or required interfaces.",
            solution: "Example: The system must be GDPR-compliant and support the existing financial-accounting interface.",
          },
        ],
      },
      processMining: {
        nav: "Process Mining",
        title: "Event logs, rules and flattening",
        copy: "Process mining reconstructs and checks processes using event data. The decisive ideas are case notion, object reference and event order.",
        learningGoals: ["Read event logs", "Detect rule violations", "Explain flattening by object type"],
        explanation: "Classic process mining uses one case, such as an order. Object-centric process mining considers several objects at once, such as order, item and parcel. Flattening reduces this view to one object type and may lose relationships.",
        concepts: [["Event", "Activity with timestamp and object reference."], ["Case", "Process instance along which events are ordered."], ["Flattening", "Object-centric log is mapped to one case type."]],
        visualization: { title: "Event-log timeline", type: "event-log", events: [["10:00", "Order created", "Order O1"], ["10:04", "Item added", "Item I1"], ["10:10", "Parcel shipped", "Parcel P1"], ["10:12", "Payment received", "Order O1"]] },
        guidedTasks: [
          {
            type: "multi",
            level: 3,
            title: "Mark rule violation",
            question: "Rule: A parcel may only be shipped after payment. Which event is problematic?",
            choices: ["10:10 Parcel shipped", "10:12 Payment received", "10:04 Item added", "10:00 Order created"],
            answer: ["10:10 Parcel shipped"],
            hint: "Compare the timestamps of shipment and payment.",
            explanation: "The parcel is shipped at 10:10, but payment arrives only at 10:12. The shipment violates the rule.",
            solution: "The problematic event is 10:10 Parcel shipped.",
          },
        ],
        examTasks: [
          {
            type: "text",
            level: 4,
            title: "Explain object centricity",
            question: "Why can object-centric process mining be more informative than a log flattened by order?",
            answer: ["multiple", "objects", "relationships"],
            hint: "Think of order, item and parcel at the same time.",
            explanation: "OCPM preserves relationships between several object types. Flattening can duplicate events or lose relationships.",
            solution: "OCPM considers multiple object types and their relationships; a flat case log can distort these relationships.",
          },
        ],
      },
    },
  },
};
